databases:
  - name: first_site_djangodb
    plan: free
    databaseName: first_site_django
    user: wallison

services:
  - type: web
    plan: free
    name: first_site_django
    runtime: python
    startCommand: "python -m gunicorn first_site_django.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: first_site_djangodb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
